### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by udjfvnsaoepna** [porthole-ascend-cinnamon/mhddos_proxy#1]
Server: Ubuntu 20

Error:
```
Traceback (most recent call last):
  File "./start.py", line 1287, in <module>
    exit('Cannot resolve hostname ', url.host, e)
  File "./start.py", line 73, in exit
    logger.error(" ".join(message))
TypeError: sequence item 2: expected str instance, gaierror found
Traceback (most recent call last):
  File "./start.py", line 1285, in <module>
    host = gethostbyname(url.host)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./start.py", line 1287, in <module>
    exit('Cannot resolve hostname ', url.host, e)
  File "./start.py", line 73, in exit
    logger.error(" ".join(message))
TypeError: sequence item 2: expected str instance, gaierror found
Traceback (most recent call last):
  File "./start.py", line 1285, in <module>
    host = gethostbyname(url.host)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./start.py", line 1287, in <module>
    exit('Cannot resolve hostname ', url.host, e)
  File "./start.py", line 73, in exit
    logger.error(" ".join(message))
TypeError: sequence item 2: expected str instance, gaierror found
Traceback (most recent call last):
  File "./start.py", line 1285, in <module>
    host = gethostbyname(url.host)
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by porthole-ascend-cinnamon** [comment]
Hi, thanks for the report. The error happens on MHDDoS level which I don't have control over, but I will try to help. This have been reported several times but I never encountered it myself.
It seems to be DNS resolving issue - you can try entering IP address instead of hostname.
I also need the command that you've used.

**Comment by porthole-ascend-cinnamon** [comment]
UPD: Now the hosts is resolved on startup, this should eliminate errors during the attack. The host still has to be correct and resolvable, ofc.

**Comment by udjfvnsaoepna** [comment]
Please add config with targets
Like in DB1000N

**Comment by niksoluv** [comment]
![image](https://user-images.githubusercontent.com/55049006/157747543-aa4c851c-d886-4a12-a74f-5414d30ba706.png)
have such issue, don't know what to do

**Comment by porthole-ascend-cinnamon** [comment]
UPD2: It's incorrect to resolve hostnames, because most HTTP servers will reject the direct IP requests. Unfortunately, due to MHDDoS (non-existing) code structure, I cannot wrap it directly, so we are stuck with the provided interface, which requires original URLs to pass correct Host: (and other) headers to the target. 
Reverting the change.

As for the config targets, it's being considered. Please open a new request with more details - do you want to use local file or remote file, or both?
