### ISSUE TITLE
Reasons behind choosing executable only model of distribution!

### ISSUE THREAD

**Issue by orlovskyjavaprofi** [porthole-ascend-cinnamon/mhddos_proxy#188]
Hi all !
Glory to Ukraine !
Together we win!
So i am kind of puzzled why the main developers of this project decided to **go full executable,** i know we live in strange times, still can you explain me  why you have chosen such strange format of distribution for the mhddos_proxy?

I mean an executable python app, why  just  not simply speak to other groups of devs which depend on your project and find common ground so they can verify the code , find bugs and fixed and put in your private repo?
Speak to them, they dont bite ,because honestly the fork of mhddos_proxy is real thing and i personally dont wish to maintain it ,but if circumstances arise and need for such fork will be there i think you will understand that other part of our community demand and have right to see code which they execute.  
Your code is not under any license , so legally speaking this would be ok, still i hope that we can find a common ground and find suitable solution for all of us, we doing one and the same job , we dont need to argue about.

I hope you understand what i meaning and i hope to hear from you soon!

**Comment by porthole-ascend-cinnamon** [comment]
I've kinda tried to provide reasons in the readme without going deep into the details.
It should be pretty obvious, that open-source option gives weapon to anyone with unknown intentions, and we don't want that. Same way you don't disclose the location of the military units, why make public what is actually a remote control for your MRLS systems for enemy to abuse?

IMHO, this should've been done much earlier, but it is what it is. The public version it there to stay for the foreseeable future, but we are trying to limit further possible damage.

I feel your concerns, and hope we've built enough trust at this point to make a transition. Most users never read the code anyway (did you?), it's more about the feeling than actual security. There are obfuscated scripts in current version, and unless you've broken the protection which I doubt - you don't know what is going on there anyways.

You can (always could) make a fork, but since I haven't seen any of your PRs, I wonder what would that be for. I am not aware of any "groups of devs" we should speak to, there are 2 core devs which spend weeks of their time on this project, and that's it for the _most_ part. You are always welcome to open [an issue](https://github.com/porthole-ascend-cinnamon/mhddos_proxy_releases/issues) with report or suggestion.

**Comment by orlovskyjavaprofi** [comment]
I understand your reasons, still i would raise my concerns and my company policy for security stuff  is to use only full opensource tools or tools where which we can audit under NDA.
My company and i we will switch to db1000n , sorry , but this how we do cyber stuff in Germany.

I wish you all the best !
Glory to Ukraine!

**Comment by porthole-ascend-cinnamon** [comment]
Well, you can still use the public version, without proxies it would be more or less same stuff as db1000n. Wish you luck!
