### ISSUE TITLE
Is it possible to disable proxy searching?

### ISSUE THREAD

**Issue by Artist42** [porthole-ascend-cinnamon/mhddos_proxy#9]
Because if I testing, for example, 2 ports and with TCP and with UDP connections, then I need VPN for UDP, and proxy is useless in that case. It's just slowing down my tests. Thank you for helping.

**Comment by porthole-ascend-cinnamon** [comment]
It's not possible to disable proxy searching since it's the main proposition of this package - no need to search for VPN / proxies. 
I am even considering deprecating UDP support, since it seems out-of-place with VPN requirement. I added it for the sake of completeness so you don't need to download another tool, but I recommend against mixing UDP with other types - either use only UPD under VPN (in this case proxy search is disabled), or use http | tcp targets without VPN.
Alternatively, If you already have good paid VPN, you can use plain MHDDoS or DDoS-Ripper.

**Comment by Artist42** [comment]
Problem is that MHDDos doesn`t have option for multiple targets, wich you have
